proxy-groups:
  - name: 节点选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png
    type: select
    proxies:
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: YouTube
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Google
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: ChatGPT
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: GitHub
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Twitter
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Microsoft
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    type: select
    proxies:
      - 全部节点
      - DIRECT
  - name: TikTok
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok_1.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Telegram
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Netflix
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Instagram
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Instagram.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: PayPal
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/PayPal.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: Apple
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png
    type: select
    proxies:
      - 香港自动
      - 全部节点
      - DIRECT
  - name: 全球直连
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 漏网之鱼
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 香港节点
      - 日本节点
      - 美国节点
      - 狮城节点
      - 韩国节点
      - 自动选择
      - 香港自动
      - 全部节点
      - DIRECT
  - name: 台湾节点
    icon: https://gh.fusir.eu.org/https://raw.githubusercontent.com/scongf/rule/refs/heads/master/tw.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    type: select
  - name: 香港节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    type: select
  - name: 日本节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    type: select
  - name: 美国节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    type: select
  - name: 狮城节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    type: select
  - name: 韩国节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png
    include-all: true
    filter: (?i)KR|Korea|KOR|首尔|韩|韓
    type: select
  - name: 自动选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    interval: 300
    tolerance: 50
  - name: 香港自动
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    type: select
    interval: 300
    tolerance: 50
  - name: 全部节点
    icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select

rule-providers:
  LocalAreaNetwork:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Google:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    path: ./ruleset/Google.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Twitter:
    url: https://gh.fusir.eu.org/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/Twitter.list
    path: ./ruleset/Twitter.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GitHub:
    url: https://gh.fusir.eu.org/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/Github.list
    path: ./ruleset/Github.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChatGPT:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  TikTok:
    url: https://gh.fusir.eu.org/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/TikTok.list
    path: ./ruleset/TikTok.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Instagram:
    url: https://gh.fusir.eu.org/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/Instagram.list
    path: ./ruleset/Instagram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  PayPal:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.list
    path: ./ruleset/PayPal.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Steam:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  YouTube:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Netflix:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  ChinaCompanyIp:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://gh.fusir.eu.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http

rules:
  - "RULE-SET,LocalAreaNetwork,全球直连"
  - "RULE-SET,UnBan,全球直连"
  - "RULE-SET,Google,Google"
  - "RULE-SET,GoogleCN,全球直连"
  - "RULE-SET,Twitter,Twitter"
  - "RULE-SET,GitHub,GitHub"
  - "RULE-SET,Microsoft,Microsoft"
  - "RULE-SET,Apple,Apple"
  - "RULE-SET,Telegram,Telegram"
  - "RULE-SET,ChatGPT,ChatGPT"
  - "RULE-SET,TikTok,TikTok"
  - "RULE-SET,Instagram,Instagram"
  - "RULE-SET,PayPal,PayPal"
  - "RULE-SET,Steam,Telegram"
  - "RULE-SET,YouTube,YouTube"
  - "RULE-SET,Netflix,Netflix"
  - "RULE-SET,ProxyGFWlist,节点选择"
  - "RULE-SET,ChinaDomain,全球直连"
  - "RULE-SET,ChinaCompanyIp,全球直连"
  - "RULE-SET,Download,全球直连"
  - "GEOIP,CN,全球直连"
  - "MATCH,漏网之鱼"
